/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.ch.qos.logback.logback.classic)
    api(libs.org.apache.logging.log4j.log4j.to.slf4j)
    api(libs.org.slf4j.jul.to.slf4j)
    api(libs.jakarta.validation.jakarta.validation.api)
    api(libs.org.springframework.spring.core)
    api(libs.org.projectlombok.lombok)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.hibernate.validator.hibernate.validator)
}

description = "micro-common"

java {
    withJavadocJar()
}
