/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(project(":micro-spring-boot-starter"))
    api(project(":micro-auth-casdoor"))
    api(project(":micro-pic-upload-starter"))
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    api(libs.org.projectlombok.lombok)
    testImplementation(project(":micro-test"))
    testImplementation(libs.org.springframework.spring.webflux)
    testImplementation(libs.io.projectreactor.reactor.test)
}

description = "demo-backend"

java {
    withJavadocJar()
}
