/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.github.binarywang.weixin.java.miniapp)
    api(libs.io.jsonwebtoken.jjwt.api)
    api(project(":micro-auth"))
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    api(libs.org.projectlombok.lombok)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.impl)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.jackson)
    testImplementation(project(":micro-test"))
}

description = "micro-auth"

java {
    withJavadocJar()
}
