# Use root/example as user/password credentials
version: '3.1'

services:

  casdoor:
    container_name: casdoor
    image: casbin/casdoor-all-in-one
    restart: unless-stopped
    ports:
      - "28000:8000"