/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "parent"
include(":demo-reactive")
include(":micro-auth-wechat")
include(":demo-backend")
include(":micro-dependencies")
include(":micro-common")
include(":micro-auth-casdoor")
include(":micro-web")
include(":micro-test")
include(":micro-pic-upload-starter")
include(":micro-auth")
include(":micro-spring-boot-starter")
include(":micro-sql-jooq")
