/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq.keys


import com.jiangtj.micro.payment.jooq.tables.PaymentRecord
import com.jiangtj.micro.payment.jooq.tables.records.PaymentRecordRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val KEY_PAYMENT_RECORD_PRIMARY: UniqueKey<PaymentRecordRecord> = Internal.createUniqueKey(PaymentRecord.PAYMENT_RECORD, DSL.name("KEY_payment_record_PRIMARY"), arrayOf(PaymentRecord.PAYMENT_RECORD.ID), true)
