/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq.tables.references


import com.jiangtj.micro.payment.jooq.tables.PaymentRecord



/**
 * 支付记录
 */
val PAYMENT_RECORD: PaymentRecord = PaymentRecord.PAYMENT_RECORD
