/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq.indexes


import com.jiangtj.micro.payment.jooq.tables.PaymentMain
import com.jiangtj.micro.payment.jooq.tables.PaymentRefund

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val PAYMENT_MAIN_IDX_ORDER_NO: Index = Internal.createIndex(DSL.name("idx_order_no"), PaymentMain.PAYMENT_MAIN, arrayOf(PaymentMain.PAYMENT_MAIN.ORDER_NO), false)
val PAYMENT_REFUND_IDX_ORDER_NO: Index = Internal.createIndex(DSL.name("idx_order_no"), PaymentRefund.PAYMENT_REFUND, arrayOf(PaymentRefund.PAYMENT_REFUND.ORDER_NO), false)
val PAYMENT_REFUND_IDX_PAYMENT_ID: Index = Internal.createIndex(DSL.name("idx_payment_id"), PaymentRefund.PAYMENT_REFUND, arrayOf(PaymentRefund.PAYMENT_REFUND.PAYMENT_ID), false)
val PAYMENT_REFUND_IDX_REFUND_NO: Index = Internal.createIndex(DSL.name("idx_refund_no"), PaymentRefund.PAYMENT_REFUND, arrayOf(PaymentRefund.PAYMENT_REFUND.REFUND_NO), false)
val PAYMENT_MAIN_IDX_USER_ID: Index = Internal.createIndex(DSL.name("idx_user_id"), PaymentMain.PAYMENT_MAIN, arrayOf(PaymentMain.PAYMENT_MAIN.USER_ID), false)
