/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq.indexes


import com.jiangtj.micro.payment.jooq.tables.PaymentRecord

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val PAYMENT_RECORD_IDX_ORDER_ID: Index = Internal.createIndex(DSL.name("idx_order_id"), PaymentRecord.PAYMENT_RECORD, arrayOf(PaymentRecord.PAYMENT_RECORD.ORDER_ID), false)
val PAYMENT_RECORD_IDX_PAYMENT_ID: Index = Internal.createIndex(DSL.name("idx_payment_id"), PaymentRecord.PAYMENT_RECORD, arrayOf(PaymentRecord.PAYMENT_RECORD.PAYMENT_ID), false)
val PAYMENT_RECORD_IDX_USER_ID: Index = Internal.createIndex(DSL.name("idx_user_id"), PaymentRecord.PAYMENT_RECORD, arrayOf(PaymentRecord.PAYMENT_RECORD.USER_ID), false)
