/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq.tables.pojos


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.math.BigDecimal
import java.time.LocalDateTime


/**
 * 支付退款记录
 */
@Suppress("UNCHECKED_CAST")
data class PaymentRefund(
    var id: Int? = null,
    var createTime: LocalDateTime? = null,
    var modifyTime: LocalDateTime? = null,
    @get:NotNull
    @get:Size(max = 50)
    var refundNo: String? = null,
    @get:NotNull
    @get:Size(max = 50)
    var orderNo: String? = null,
    @get:NotNull
    var paymentId: Int? = null,
    @get:Size(max = 50)
    var channelRefundId: String? = null,
    @get:NotNull
    var amount: BigDecimal? = null,
    @get:NotNull
    var status: Byte? = null,
    var refundTime: LocalDateTime? = null
): Serializable {

}
