/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq.tables.pojos


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size
import org.jooq.JSON
import java.io.Serializable
import java.time.LocalDateTime


/**
 * 支付回调
 */
@Suppress("UNCHECKED_CAST")
data class PaymentCallback(
    var id: Int? = null,
    var createTime: LocalDateTime? = null,
    var modifyTime: LocalDateTime? = null,
    @get:NotNull
    var type: Byte? = null,
    @get:NotNull
    @get:Size(max = 50)
    var orderNo: String? = null,
    @get:NotNull
    @get:Size(max = 50)
    var transactionId: String? = null,
    @get:NotNull
    var status: Byte? = null,
    @get:NotNull
    var callbackInfo: JSON? = null
): Serializable {

}
