/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":micro-common"))
    api(project(":micro-auth"))
    api(libs.org.springframework.boot.spring.boot.starter.test)
    api(libs.org.projectlombok.lombok)
    api(libs.io.projectreactor.reactor.test)
}

description = "micro-test"

java {
    withJavadocJar()
}
