/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":micro-web"))
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.springframework.spring.web)
    api(libs.org.springframework.spring.context)
    api(libs.org.hibernate.validator.hibernate.validator)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.org.springframework.boot.spring.boot.starter.cache)
    api(libs.com.github.ben.manes.caffeine.caffeine)
    api(libs.org.apache.tomcat.embed.tomcat.embed.core)
    api(libs.org.springframework.spring.webflux)
    api(libs.org.springframework.spring.webmvc)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    api(libs.org.projectlombok.lombok)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "micro-spring-boot-starter"

java {
    withJavadocJar()
}
