/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":micro-common"))
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.springframework.spring.web)
    api(libs.org.springframework.boot.spring.boot.starter.aop)
    api(libs.org.springframework.spring.webmvc)
    api(libs.org.apache.tomcat.embed.tomcat.embed.core)
    api(libs.io.projectreactor.reactor.core)
    api(libs.org.projectlombok.lombok)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "micro-web"

java {
    withJavadocJar()
}
