/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.aliyun.oss.aliyun.sdk.oss)
    api(libs.com.huaweicloud.esdk.obs.java.bundle)
    api(libs.io.minio.minio)
    api(project(":micro-common"))
    api(project(":micro-web"))
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.springframework.spring.web)
    api(libs.org.springframework.spring.context)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    api(libs.org.projectlombok.lombok)
    api(libs.org.springframework.spring.webmvc)
    api(libs.org.springframework.spring.webflux)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "micro-pic-upload-starter"

java {
    withJavadocJar()
}
