/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq.tables.records


import com.jiangtj.micro.payment.jooq.tables.PaymentCallback
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size
import org.jooq.JSON
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime


/**
 * 支付回调
 */
@Suppress("UNCHECKED_CAST")
open class PaymentCallbackRecord() : UpdatableRecordImpl<PaymentCallbackRecord>(PaymentCallback.PAYMENT_CALLBACK) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var createTime: LocalDateTime?
        set(value): Unit = set(1, value)
        get(): LocalDateTime? = get(1) as LocalDateTime?

    open var modifyTime: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    @get:NotNull
    @get:Size(max = 50)
    open var notifyId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    @get:NotNull
    open var type: Byte?
        set(value): Unit = set(4, value)
        get(): Byte? = get(4) as Byte?

    @get:NotNull
    @get:Size(max = 50)
    open var orderNo: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    @get:NotNull
    @get:Size(max = 50)
    open var transactionId: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    @get:NotNull
    open var status: Byte?
        set(value): Unit = set(7, value)
        get(): Byte? = get(7) as Byte?

    @get:NotNull
    open var callbackInfo: JSON?
        set(value): Unit = set(8, value)
        get(): JSON? = get(8) as JSON?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised PaymentCallbackRecord
     */
    constructor(id: Int? = null, createTime: LocalDateTime? = null, modifyTime: LocalDateTime? = null, notifyId: String? = null, type: Byte? = null, orderNo: String? = null, transactionId: String? = null, status: Byte? = null, callbackInfo: JSON? = null): this() {
        this.id = id
        this.createTime = createTime
        this.modifyTime = modifyTime
        this.notifyId = notifyId
        this.type = type
        this.orderNo = orderNo
        this.transactionId = transactionId
        this.status = status
        this.callbackInfo = callbackInfo
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised PaymentCallbackRecord
     */
    constructor(value: com.jiangtj.micro.payment.jooq.tables.pojos.PaymentCallback?): this() {
        if (value != null) {
            this.id = value.id
            this.createTime = value.createTime
            this.modifyTime = value.modifyTime
            this.notifyId = value.notifyId
            this.type = value.type
            this.orderNo = value.orderNo
            this.transactionId = value.transactionId
            this.status = value.status
            this.callbackInfo = value.callbackInfo
            resetChangedOnNotNull()
        }
    }
}
