/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq.tables.records


import com.jiangtj.micro.payment.jooq.tables.PaymentMain
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.math.BigDecimal
import java.time.LocalDateTime


/**
 * 支付记录
 */
@Suppress("UNCHECKED_CAST")
open class PaymentMainRecord() : UpdatableRecordImpl<PaymentMainRecord>(PaymentMain.PAYMENT_MAIN) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var createTime: LocalDateTime?
        set(value): Unit = set(1, value)
        get(): LocalDateTime? = get(1) as LocalDateTime?

    open var modifyTime: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    @get:NotNull
    @get:Size(max = 50)
    open var orderNo: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    @get:NotNull
    @get:Size(max = 50)
    open var paymentNo: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    @get:Size(max = 50)
    open var transactionId: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    @get:NotNull
    @get:Size(max = 50)
    open var userId: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    @get:NotNull
    open var amount: BigDecimal?
        set(value): Unit = set(7, value)
        get(): BigDecimal? = get(7) as BigDecimal?

    @get:NotNull
    open var status: Byte?
        set(value): Unit = set(8, value)
        get(): Byte? = get(8) as Byte?

    open var paymentTime: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    @get:NotNull
    open var paymentMethod: Byte?
        set(value): Unit = set(10, value)
        get(): Byte? = get(10) as Byte?

    @get:NotNull
    @get:Size(max = 50)
    open var paymentChannel: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised PaymentMainRecord
     */
    constructor(id: Int? = null, createTime: LocalDateTime? = null, modifyTime: LocalDateTime? = null, orderNo: String? = null, paymentNo: String? = null, transactionId: String? = null, userId: String? = null, amount: BigDecimal? = null, status: Byte? = null, paymentTime: LocalDateTime? = null, paymentMethod: Byte? = null, paymentChannel: String? = null): this() {
        this.id = id
        this.createTime = createTime
        this.modifyTime = modifyTime
        this.orderNo = orderNo
        this.paymentNo = paymentNo
        this.transactionId = transactionId
        this.userId = userId
        this.amount = amount
        this.status = status
        this.paymentTime = paymentTime
        this.paymentMethod = paymentMethod
        this.paymentChannel = paymentChannel
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised PaymentMainRecord
     */
    constructor(value: com.jiangtj.micro.payment.jooq.tables.pojos.PaymentMain?): this() {
        if (value != null) {
            this.id = value.id
            this.createTime = value.createTime
            this.modifyTime = value.modifyTime
            this.orderNo = value.orderNo
            this.paymentNo = value.paymentNo
            this.transactionId = value.transactionId
            this.userId = value.userId
            this.amount = value.amount
            this.status = value.status
            this.paymentTime = value.paymentTime
            this.paymentMethod = value.paymentMethod
            this.paymentChannel = value.paymentChannel
            resetChangedOnNotNull()
        }
    }
}
