/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.micro.payment.jooq


import com.jiangtj.micro.payment.jooq.tables.PaymentRecord
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultSchema : SchemaImpl("", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA: DefaultSchema = DefaultSchema()
    }

    /**
     * 支付记录
     */
    val PAYMENT_RECORD: PaymentRecord get() = PaymentRecord.PAYMENT_RECORD

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        PaymentRecord.PAYMENT_RECORD
    )
}
