/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":micro-common"))
    api(libs.org.springframework.boot.spring.boot.starter.jooq)
    api(libs.org.springframework.data.spring.data.commons)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    api(libs.org.projectlombok.lombok)
    api(libs.org.jooq.jooq.meta)
    api(libs.org.jooq.jooq.codegen)
    api(libs.io.projectreactor.reactor.core)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "micro-sql-jooq"

java {
    withJavadocJar()
}
